use crate::models::*;
use std::collections::HashMap;

/// Returns standard Rarity configs ('R', 'SR', 'SSR', 'UR')
pub fn default_rarity_configs() -> HashMap<String, RarityConfig> {
    let mut map = HashMap::new();
    map.insert(
        "R".to_string(),
        RarityConfig {
            rarity_id: "R".to_string(),
            display_name: "Thường".to_string(),
            base_stat_multiplier: 1.00,
            growth_rate_per_level: 0.050,
            max_star_rating: 5,
            max_skills_allowed: 2,
        },
    );
    map.insert(
        "SR".to_string(),
        RarityConfig {
            rarity_id: "SR".to_string(),
            display_name: "Hiếm".to_string(),
            base_stat_multiplier: 1.20,
            growth_rate_per_level: 0.075,
            max_star_rating: 6,
            max_skills_allowed: 3,
        },
    );
    map.insert(
        "SSR".to_string(),
        RarityConfig {
            rarity_id: "SSR".to_string(),
            display_name: "Cực Phẩm".to_string(),
            base_stat_multiplier: 1.50,
            growth_rate_per_level: 0.100,
            max_star_rating: 7,
            max_skills_allowed: 4,
        },
    );
    map.insert(
        "UR".to_string(),
        RarityConfig {
            rarity_id: "UR".to_string(),
            display_name: "Thần Tướng".to_string(),
            base_stat_multiplier: 1.85,
            growth_rate_per_level: 0.135,
            max_star_rating: 9,
            max_skills_allowed: 5,
        },
    );
    map
}

/// Returns standard Formation Line configs (FRONT, MID, BACK)
pub fn default_formation_line_configs() -> Vec<FormationLineConfig> {
    vec![
        FormationLineConfig {
            line_type: FormationLineType::Front,
            display_name: "Hàng Đầu".to_string(),
            slot_indices: vec![1, 2, 3],
            allowed_roles: vec![CardRole::Vanguard, CardRole::Warrior],
            penalty_roles: vec![CardRole::Marksman, CardRole::Support],
            penalty_stats: LinePenaltyStats {
                damage_taken_pct: Some(0.20),
                aggro_reduction_pct: None,
                speed_reduction_pct: None,
            },
            line_buffs: LineBuffs {
                hp_pct: Some(0.15),
                def_pct: Some(0.12),
                crit_res_pct: Some(0.05),
                ..Default::default()
            },
        },
        FormationLineConfig {
            line_type: FormationLineType::Mid,
            display_name: "Hàng Giữa".to_string(),
            slot_indices: vec![4, 5, 6],
            allowed_roles: vec![
                CardRole::Warrior,
                CardRole::Assassin,
                CardRole::Marksman,
                CardRole::Mage,
            ],
            penalty_roles: vec![],
            penalty_stats: LinePenaltyStats::default(),
            line_buffs: LineBuffs {
                dmg_dealt_pct: Some(0.08),
                crit_rate_pct: Some(0.10),
                armor_pen_pct: Some(0.05),
                ..Default::default()
            },
        },
        FormationLineConfig {
            line_type: FormationLineType::Back,
            display_name: "Hàng Sau".to_string(),
            slot_indices: vec![7, 8, 9],
            allowed_roles: vec![
                CardRole::Marksman,
                CardRole::Mage,
                CardRole::Tactician,
                CardRole::Support,
            ],
            penalty_roles: vec![CardRole::Vanguard],
            penalty_stats: LinePenaltyStats {
                damage_taken_pct: None,
                aggro_reduction_pct: Some(0.30),
                speed_reduction_pct: Some(0.15),
            },
            line_buffs: LineBuffs {
                speed_flat: Some(10.0),
                initial_morale_flat: Some(25),
                cc_success_pct: Some(0.15),
                ..Default::default()
            },
        },
    ]
}

/// Returns sample seed skills
pub fn default_master_skills() -> Vec<SkillRow> {
    vec![
        SkillRow {
            skill_id: "skill_guanyu_ult".to_string(),
            name: "Uy Chấn Hoa Hạ".to_string(),
            skill_quality: "LEGENDARY".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "PIERCE_ROW".to_string(),
            target_rule: "ENEMY_NEAREST".to_string(),
            damage_type: "PHYSICAL".to_string(),
            damage_multiplier: 2.80,
            can_crit: true,
            effects_applied: vec![
                SkillEffect {
                    status_type: "Stun".to_string(),
                    target: "PrimaryTarget".to_string(),
                    chance: 0.40,
                    value: None,
                    duration_turns: 1,
                },
                SkillEffect {
                    status_type: "ArmorBreak".to_string(),
                    target: "AllTargetsInScope".to_string(),
                    chance: 1.00,
                    value: Some(-0.30),
                    duration_turns: 2,
                },
            ],
            description: Some(
                "Chém dọc toàn bộ một hàng ngang, gây sát thương lớn và giảm giáp".to_string(),
            ),
        },
        SkillRow {
            skill_id: "skill_guanyu_normal".to_string(),
            name: "Thanh Long Trảm".to_string(),
            skill_quality: "COMMON".to_string(),
            is_skill_common: false,
            trigger_type: "NORMAL_ATTACK".to_string(),
            execution_priority: 3,
            cost_morale: 0,
            cooldown_turns: 0,
            target_pattern: "DIRECT_LANE".to_string(),
            target_rule: "ENEMY_NEAREST".to_string(),
            damage_type: "PHYSICAL".to_string(),
            damage_multiplier: 1.00,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Đòn đánh thường tích lũy 25 sĩ khí".to_string()),
        },
        SkillRow {
            skill_id: "skill_zhao_yun_ult".to_string(),
            name: "Thất Tiến Thất Xuất".to_string(),
            skill_quality: "EPIC".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "TARGET_LOWEST_HP".to_string(),
            target_rule: "ENEMY_LOWEST_HP".to_string(),
            damage_type: "PHYSICAL".to_string(),
            damage_multiplier: 2.20,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Xông vào mục tiêu yếu máu nhất, tăng 40% Né đòn và phản kích".to_string()),
        },
        SkillRow {
            skill_id: "skill_huang_zhong_ult".to_string(),
            name: "Bách Bộ Xuyên Dương".to_string(),
            skill_quality: "EPIC".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "PIERCE_ROW".to_string(),
            target_rule: "ENEMY_NEAREST".to_string(),
            damage_type: "PHYSICAL".to_string(),
            damage_multiplier: 2.50,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Bắn xuyên mục tiêu đứng sau khiên; sát thương tăng theo cự ly".to_string()),
        },
        SkillRow {
            skill_id: "skill_zhuge_liang_ult".to_string(),
            name: "Đông Phong Triệu Hoán".to_string(),
            skill_quality: "LEGENDARY".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "COLUMN".to_string(),
            target_rule: "ENEMY_NEAREST".to_string(),
            damage_type: "MAGIC".to_string(),
            damage_multiplier: 2.00,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Thổi lùi hàng trước địch về hàng giữa và gây choáng 1 hiệp".to_string()),
        },
        SkillRow {
            skill_id: "skill_cao_cao_ult".to_string(),
            name: "Hiệp Thiên Tử".to_string(),
            skill_quality: "LEGENDARY".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "HIGHEST_ATK".to_string(),
            target_rule: "ENEMY_HIGHEST_ATK".to_string(),
            damage_type: "MAGIC".to_string(),
            damage_multiplier: 1.80,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Tăng công tướng Ngụy xung quanh và giảm Nộ địch công cao nhất".to_string()),
        },
        SkillRow {
            skill_id: "skill_dian_wei_ult".to_string(),
            name: "Thiết Kích Chắn Cửa".to_string(),
            skill_quality: "EPIC".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "COLUMN".to_string(),
            target_rule: "ENEMY_NEAREST".to_string(),
            damage_type: "PHYSICAL".to_string(),
            damage_multiplier: 1.60,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Khiêu khích ba ô đối diện và phản lại 25% sát thương nhận vào".to_string()),
        },
        SkillRow {
            skill_id: "skill_guo_jia_ult".to_string(),
            name: "Thập Thắng Thập Bại".to_string(),
            skill_quality: "EPIC".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "HIGHEST_ATK".to_string(),
            target_rule: "ENEMY_HIGHEST_ATK".to_string(),
            damage_type: "MAGIC".to_string(),
            damage_multiplier: 1.90,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Đóng băng địch có Nộ cao nhất và khóa thanh Nộ trong 2 lượt".to_string()),
        },
        SkillRow {
            skill_id: "skill_sun_ce_ult".to_string(),
            name: "Bá Vương Tả Đãng".to_string(),
            skill_quality: "EPIC".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "CROSS_PLUS".to_string(),
            target_rule: "ENEMY_NEAREST".to_string(),
            damage_type: "PHYSICAL".to_string(),
            damage_multiplier: 2.10,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Quét hình chữ T và hút 20% công của mục tiêu trúng đòn".to_string()),
        },
        SkillRow {
            skill_id: "skill_lu_xun_ult".to_string(),
            name: "Hỏa Thiêu Liên Doanh".to_string(),
            skill_quality: "LEGENDARY".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "PIERCE_ROW".to_string(),
            target_rule: "ENEMY_NEAREST".to_string(),
            damage_type: "MAGIC".to_string(),
            damage_multiplier: 2.20,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Đặt ấn lửa lên một tuyến; mục tiêu bị đánh sẽ phát nổ lan".to_string()),
        },
        SkillRow {
            skill_id: "skill_da_qiao_xiao_qiao_ult".to_string(),
            name: "Quốc Sắc Lưu Hương".to_string(),
            skill_quality: "LEGENDARY".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "ALL_ALLIES".to_string(),
            target_rule: "SELF_ALLY".to_string(),
            damage_type: "NONE".to_string(),
            damage_multiplier: 1.50,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Hồi máu theo công cho hàng sau và xóa mọi hiệu ứng bất lợi".to_string()),
        },
        SkillRow {
            skill_id: "skill_zhang_he_ult".to_string(),
            name: "Tập Kích Hậu Tuyến".to_string(),
            skill_quality: "EPIC".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "BACKLINE_ASSASSIN".to_string(),
            target_rule: "ENEMY_NEAREST".to_string(),
            damage_type: "PHYSICAL".to_string(),
            damage_multiplier: 2.60,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Nhảy ra sau xạ thủ/pháp sư địch để dồn sát thương chí mạng".to_string()),
        },
        SkillRow {
            skill_id: "skill_hua_tuo_ult".to_string(),
            name: "Thanh Nang Di Thư".to_string(),
            skill_quality: "LEGENDARY".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "ALL_ALLIES".to_string(),
            target_rule: "SELF_ALLY".to_string(),
            damage_type: "NONE".to_string(),
            damage_multiplier: 1.80,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Hồi máu diện rộng và có 30% cơ hội hồi sinh đồng minh".to_string()),
        },
        SkillRow {
            skill_id: "skill_jia_xu_ult".to_string(),
            name: "Loạn Vũ Độc Kế".to_string(),
            skill_quality: "EPIC".to_string(),
            is_skill_common: false,
            trigger_type: "ULTIMATE".to_string(),
            execution_priority: 1,
            cost_morale: 100,
            cooldown_turns: 0,
            target_pattern: "ALL_BOARD".to_string(),
            target_rule: "ENEMY_NEAREST".to_string(),
            damage_type: "MAGIC".to_string(),
            damage_multiplier: 1.80,
            can_crit: true,
            effects_applied: vec![],
            description: Some("Đầu độc toàn bộ địch, giảm 50% khả năng hồi phục máu".to_string()),
        },
    ]
}

/// Returns sample seed card templates
pub fn default_master_templates() -> Vec<CardTemplateRow> {
    vec![
        CardTemplateRow {
            card_template_id: "hero_guan_yu".to_string(),
            name: "Quan Vũ".to_string(),
            title: Some("Võ Thánh".to_string()),
            faction: "SHU".to_string(),
            rarity_id: "SSR".to_string(),
            recommended_role: "WARRIOR".to_string(),
            base_hp: 4200,
            base_atk: 780,
            base_def: 360,
            base_speed: 105,
            base_crit_rate: 0.150,
            base_crit_dmg: 1.500,
            base_block_rate: 0.000,
            base_dodge_rate: 0.050,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "zhao_yun".to_string(),
            name: "Triệu Vân".to_string(),
            title: Some("Thường Sơn Triệu Tử Long".to_string()),
            faction: "SHU".to_string(),
            rarity_id: "SSR".to_string(),
            recommended_role: "WARRIOR".to_string(),
            base_hp: 3800,
            base_atk: 550,
            base_def: 300,
            base_speed: 105,
            base_crit_rate: 0.100,
            base_crit_dmg: 1.500,
            base_block_rate: 0.050,
            base_dodge_rate: 0.150,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "huang_zhong".to_string(),
            name: "Hoàng Trung".to_string(),
            title: Some("Thần Xạ Lão Tướng".to_string()),
            faction: "SHU".to_string(),
            rarity_id: "SSR".to_string(),
            recommended_role: "MARKSMAN".to_string(),
            base_hp: 2200,
            base_atk: 920,
            base_def: 160,
            base_speed: 100,
            base_crit_rate: 0.150,
            base_crit_dmg: 1.500,
            base_block_rate: 0.000,
            base_dodge_rate: 0.050,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "zhuge_liang".to_string(),
            name: "Gia Cát Lượng".to_string(),
            title: Some("Ngọa Long Tiên Sinh".to_string()),
            faction: "SHU".to_string(),
            rarity_id: "UR".to_string(),
            recommended_role: "TACTICIAN".to_string(),
            base_hp: 2200,
            base_atk: 920,
            base_def: 160,
            base_speed: 100,
            base_crit_rate: 0.150,
            base_crit_dmg: 1.500,
            base_block_rate: 0.000,
            base_dodge_rate: 0.050,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "cao_cao".to_string(),
            name: "Tào Tháo".to_string(),
            title: Some("Ngụy Vũ Đế".to_string()),
            faction: "WEI".to_string(),
            rarity_id: "UR".to_string(),
            recommended_role: "TACTICIAN".to_string(),
            base_hp: 3800,
            base_atk: 550,
            base_def: 300,
            base_speed: 105,
            base_crit_rate: 0.100,
            base_crit_dmg: 1.500,
            base_block_rate: 0.050,
            base_dodge_rate: 0.050,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "dian_wei".to_string(),
            name: "Điển Vi".to_string(),
            title: Some("Cổ Chi Ác Lai".to_string()),
            faction: "WEI".to_string(),
            rarity_id: "SSR".to_string(),
            recommended_role: "VANGUARD".to_string(),
            base_hp: 5000,
            base_atk: 350,
            base_def: 420,
            base_speed: 90,
            base_crit_rate: 0.050,
            base_crit_dmg: 1.500,
            base_block_rate: 0.100,
            base_dodge_rate: 0.000,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "guo_jia".to_string(),
            name: "Quách Gia".to_string(),
            title: Some("Quỷ Mưu Quân Sư".to_string()),
            faction: "WEI".to_string(),
            rarity_id: "SSR".to_string(),
            recommended_role: "MAGE".to_string(),
            base_hp: 2200,
            base_atk: 920,
            base_def: 160,
            base_speed: 100,
            base_crit_rate: 0.150,
            base_crit_dmg: 1.500,
            base_block_rate: 0.000,
            base_dodge_rate: 0.050,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "sun_ce".to_string(),
            name: "Tôn Sách".to_string(),
            title: Some("Giang Đông Tiểu Bá Vương".to_string()),
            faction: "WU".to_string(),
            rarity_id: "SSR".to_string(),
            recommended_role: "WARRIOR".to_string(),
            base_hp: 3800,
            base_atk: 550,
            base_def: 300,
            base_speed: 105,
            base_crit_rate: 0.100,
            base_crit_dmg: 1.500,
            base_block_rate: 0.050,
            base_dodge_rate: 0.050,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "lu_xun".to_string(),
            name: "Lục Tốn".to_string(),
            title: Some("Đại Đô Đốc Đông Ngô".to_string()),
            faction: "WU".to_string(),
            rarity_id: "UR".to_string(),
            recommended_role: "MAGE".to_string(),
            base_hp: 2200,
            base_atk: 920,
            base_def: 160,
            base_speed: 100,
            base_crit_rate: 0.150,
            base_crit_dmg: 1.500,
            base_block_rate: 0.000,
            base_dodge_rate: 0.050,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "da_qiao_xiao_qiao".to_string(),
            name: "Đại Kiều & Tiểu Kiều".to_string(),
            title: Some("Giang Đông Song Kiều".to_string()),
            faction: "WU".to_string(),
            rarity_id: "UR".to_string(),
            recommended_role: "SUPPORT".to_string(),
            base_hp: 3000,
            base_atk: 450,
            base_def: 240,
            base_speed: 115,
            base_crit_rate: 0.050,
            base_crit_dmg: 1.500,
            base_block_rate: 0.000,
            base_dodge_rate: 0.050,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "zhang_he_yan_liang".to_string(),
            name: "Trương Cáp & Nhan Lương".to_string(),
            title: Some("Ám Ảnh Hậu Tuyến".to_string()),
            faction: "QUN".to_string(),
            rarity_id: "SSR".to_string(),
            recommended_role: "ASSASSIN".to_string(),
            base_hp: 2400,
            base_atk: 850,
            base_def: 180,
            base_speed: 130,
            base_crit_rate: 0.250,
            base_crit_dmg: 1.750,
            base_block_rate: 0.000,
            base_dodge_rate: 0.100,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "hua_tuo".to_string(),
            name: "Hoa Đà".to_string(),
            title: Some("Thần Y Khởi Tử Hồi Sinh".to_string()),
            faction: "QUN".to_string(),
            rarity_id: "UR".to_string(),
            recommended_role: "SUPPORT".to_string(),
            base_hp: 3000,
            base_atk: 450,
            base_def: 240,
            base_speed: 115,
            base_crit_rate: 0.050,
            base_crit_dmg: 1.500,
            base_block_rate: 0.000,
            base_dodge_rate: 0.050,
            initial_morale: 50,
            max_morale: 100,
        },
        CardTemplateRow {
            card_template_id: "jia_xu".to_string(),
            name: "Giả Hủ".to_string(),
            title: Some("Độc Sĩ Quần Hùng".to_string()),
            faction: "QUN".to_string(),
            rarity_id: "SSR".to_string(),
            recommended_role: "TACTICIAN".to_string(),
            base_hp: 2200,
            base_atk: 920,
            base_def: 160,
            base_speed: 100,
            base_crit_rate: 0.150,
            base_crit_dmg: 1.500,
            base_block_rate: 0.000,
            base_dodge_rate: 0.050,
            initial_morale: 50,
            max_morale: 100,
        },
    ]
}

/// Returns default status effects
pub fn default_master_effects() -> Vec<StatusEffectRow> {
    vec![
        StatusEffectRow {
            effect_id: "eff_stun".to_string(),
            name: "Choáng".to_string(),
            effect_category: "CROWD_CONTROL".to_string(),
            stat_target: "ACTION_LOCK".to_string(),
            calculation_type: "ABSOLUTE_STATE".to_string(),
            base_value: 1.0,
            max_stacks: 1,
            duration_turns: 1,
            tick_trigger: "TURN_START".to_string(),
            is_dispellable: false,
            icon: Some("💫".to_string()),
            vfx_prefab: Some("vfx_stun_stars".to_string()),
            description: Some("Mục tiêu mất lượt hành động trong 1 hiệp".to_string()),
        },
        StatusEffectRow {
            effect_id: "eff_armor_break".to_string(),
            name: "Phá Giáp".to_string(),
            effect_category: "DEBUFF".to_string(),
            stat_target: "DEF".to_string(),
            calculation_type: "PERCENTAGE".to_string(),
            base_value: -0.30,
            max_stacks: 3,
            duration_turns: 2,
            tick_trigger: "TURN_START".to_string(),
            is_dispellable: true,
            icon: Some("🛡️".to_string()),
            vfx_prefab: Some("vfx_armor_break".to_string()),
            description: Some("Giảm 30% phòng thủ, tối đa cộng dồn 3 tầng".to_string()),
        },
        StatusEffectRow {
            effect_id: "eff_burn".to_string(),
            name: "Thiêu Đốt".to_string(),
            effect_category: "DOT".to_string(),
            stat_target: "HP".to_string(),
            calculation_type: "PERCENTAGE".to_string(),
            base_value: -0.08,
            max_stacks: 5,
            duration_turns: 3,
            tick_trigger: "TURN_END".to_string(),
            is_dispellable: true,
            icon: Some("🔥".to_string()),
            vfx_prefab: Some("vfx_burn_flame".to_string()),
            description: Some(
                "Mỗi hiệp chịu sát thương lửa bằng 8% công của người thi triển".to_string(),
            ),
        },
        StatusEffectRow {
            effect_id: "eff_freeze".to_string(),
            name: "Đóng Băng".to_string(),
            effect_category: "CROWD_CONTROL".to_string(),
            stat_target: "SPEED".to_string(),
            calculation_type: "PERCENTAGE".to_string(),
            base_value: -0.50,
            max_stacks: 1,
            duration_turns: 2,
            tick_trigger: "TURN_START".to_string(),
            is_dispellable: true,
            icon: Some("❄️".to_string()),
            vfx_prefab: Some("vfx_ice_shards".to_string()),
            description: Some("Giảm 50% tốc độ đánh và tích lũy sĩ khí".to_string()),
        },
        StatusEffectRow {
            effect_id: "eff_atk_up".to_string(),
            name: "Cuồng Nộ".to_string(),
            effect_category: "BUFF".to_string(),
            stat_target: "ATK".to_string(),
            calculation_type: "PERCENTAGE".to_string(),
            base_value: 0.25,
            max_stacks: 3,
            duration_turns: 2,
            tick_trigger: "TURN_START".to_string(),
            is_dispellable: true,
            icon: Some("⚔️".to_string()),
            vfx_prefab: Some("vfx_atk_buff".to_string()),
            description: Some("Tăng 25% lực công kích".to_string()),
        },
        StatusEffectRow {
            effect_id: "eff_shield".to_string(),
            name: "Lá Chắn Linh Hồn".to_string(),
            effect_category: "BUFF".to_string(),
            stat_target: "SHIELD".to_string(),
            calculation_type: "FLAT".to_string(),
            base_value: 300.0,
            max_stacks: 1,
            duration_turns: 2,
            tick_trigger: "ON_DAMAGED".to_string(),
            is_dispellable: true,
            icon: Some("🔰".to_string()),
            vfx_prefab: Some("vfx_holy_shield".to_string()),
            description: Some("Tạo khiên hấp thụ 300 điểm sát thương".to_string()),
        },
        StatusEffectRow {
            effect_id: "eff_holy_regen".to_string(),
            name: "Thần Ân Trị Liệu".to_string(),
            effect_category: "HOT".to_string(),
            stat_target: "HP".to_string(),
            calculation_type: "PERCENTAGE".to_string(),
            base_value: 0.10,
            max_stacks: 1,
            duration_turns: 3,
            tick_trigger: "TURN_START".to_string(),
            is_dispellable: true,
            icon: Some("✨".to_string()),
            vfx_prefab: Some("vfx_holy_regen".to_string()),
            description: Some("Mỗi hiệp hồi phục 10% lượng máu tối đa".to_string()),
        },
    ]
}

/// Returns default 3x3 board cell configs
pub fn default_master_cells() -> Vec<BoardCellConfigRow> {
    vec![
        BoardCellConfigRow {
            slot_id: 1,
            col: 0,
            row: 0,
            line_type: "FRONT".to_string(),
            terrain_type: "HIGH_GROUND".to_string(),
            tile_buff_effect_id: Some("eff_armor_break".to_string()),
            hazard_damage_pct: 0.0,
            preferred_roles: vec!["VANGUARD".to_string(), "WARRIOR".to_string()],
            penalty_roles: vec!["MARKSMAN".to_string()],
            description: Some("Tiền tuyến góc trái - Cao điểm phòng hộ".to_string()),
        },
        BoardCellConfigRow {
            slot_id: 2,
            col: 1,
            row: 0,
            line_type: "FRONT".to_string(),
            terrain_type: "NORMAL".to_string(),
            tile_buff_effect_id: None,
            hazard_damage_pct: 0.0,
            preferred_roles: vec!["VANGUARD".to_string()],
            penalty_roles: vec!["MARKSMAN".to_string(), "MAGE".to_string()],
            description: Some("Tiền tuyến chính diện - Hứng sát thương trung tâm".to_string()),
        },
        BoardCellConfigRow {
            slot_id: 3,
            col: 2,
            row: 0,
            line_type: "FRONT".to_string(),
            terrain_type: "HIGH_GROUND".to_string(),
            tile_buff_effect_id: Some("eff_armor_break".to_string()),
            hazard_damage_pct: 0.0,
            preferred_roles: vec!["VANGUARD".to_string(), "WARRIOR".to_string()],
            penalty_roles: vec!["MARKSMAN".to_string()],
            description: Some("Tiền tuyến góc phải".to_string()),
        },
        BoardCellConfigRow {
            slot_id: 4,
            col: 0,
            row: 1,
            line_type: "MID".to_string(),
            terrain_type: "NORMAL".to_string(),
            tile_buff_effect_id: None,
            hazard_damage_pct: 0.0,
            preferred_roles: vec!["WARRIOR".to_string(), "ASSASSIN".to_string()],
            penalty_roles: vec![],
            description: Some("Trung quân sườn trái".to_string()),
        },
        BoardCellConfigRow {
            slot_id: 5,
            col: 1,
            row: 1,
            line_type: "MID".to_string(),
            terrain_type: "HOLY_SANCTUARY".to_string(),
            tile_buff_effect_id: Some("eff_holy_regen".to_string()),
            hazard_damage_pct: 0.0,
            preferred_roles: vec![
                "WARRIOR".to_string(),
                "MAGE".to_string(),
                "SUPPORT".to_string(),
            ],
            penalty_roles: vec![],
            description: Some("Trọng tâm bàn cờ - Thánh đường ban phước hồi máu".to_string()),
        },
        BoardCellConfigRow {
            slot_id: 6,
            col: 2,
            row: 1,
            line_type: "MID".to_string(),
            terrain_type: "NORMAL".to_string(),
            tile_buff_effect_id: None,
            hazard_damage_pct: 0.0,
            preferred_roles: vec!["WARRIOR".to_string(), "ASSASSIN".to_string()],
            penalty_roles: vec![],
            description: Some("Trung quân sườn phải".to_string()),
        },
        BoardCellConfigRow {
            slot_id: 7,
            col: 0,
            row: 2,
            line_type: "BACK".to_string(),
            terrain_type: "SHADOW_VEIL".to_string(),
            tile_buff_effect_id: None,
            hazard_damage_pct: 0.0,
            preferred_roles: vec!["MARKSMAN".to_string(), "ASSASSIN".to_string()],
            penalty_roles: vec!["VANGUARD".to_string()],
            description: Some("Hậu quân trái - Ẩn nấp trong sương mù né aggro".to_string()),
        },
        BoardCellConfigRow {
            slot_id: 8,
            col: 1,
            row: 2,
            line_type: "BACK".to_string(),
            terrain_type: "NORMAL".to_string(),
            tile_buff_effect_id: None,
            hazard_damage_pct: 0.0,
            preferred_roles: vec!["MAGE".to_string(), "TACTICIAN".to_string()],
            penalty_roles: vec!["VANGUARD".to_string()],
            description: Some("Hậu quân trung tâm - Đứng dàn kỹ năng diện rộng".to_string()),
        },
        BoardCellConfigRow {
            slot_id: 9,
            col: 2,
            row: 2,
            line_type: "BACK".to_string(),
            terrain_type: "SHADOW_VEIL".to_string(),
            tile_buff_effect_id: None,
            hazard_damage_pct: 0.0,
            preferred_roles: vec!["MARKSMAN".to_string(), "SUPPORT".to_string()],
            penalty_roles: vec!["VANGUARD".to_string()],
            description: Some("Hậu quân phải - Vị trí cự xạ chuẩn chỉ".to_string()),
        },
    ]
}

/// Returns default hero-to-skill mappings for all 12 Three Kingdoms generals
pub fn default_master_template_skills() -> Vec<CardTemplateSkillRow> {
    vec![
        // Triệu Vân
        CardTemplateSkillRow { card_template_id: "zhao_yun".to_string(), skill_id: "zhao_yun_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "zhao_yun".to_string(), skill_id: "skill_zhao_yun_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Hoàng Trung
        CardTemplateSkillRow { card_template_id: "huang_zhong".to_string(), skill_id: "skill_huang_zhong_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "huang_zhong".to_string(), skill_id: "skill_huang_zhong_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Gia Cát Lượng
        CardTemplateSkillRow { card_template_id: "zhuge_liang".to_string(), skill_id: "skill_zhuge_liang_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "zhuge_liang".to_string(), skill_id: "skill_zhuge_liang_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Trương Cáp & Nhan Lương
        CardTemplateSkillRow { card_template_id: "zhang_he_yan_liang".to_string(), skill_id: "skill_zhang_he_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "zhang_he_yan_liang".to_string(), skill_id: "skill_zhang_he_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Hoa Đà
        CardTemplateSkillRow { card_template_id: "hua_tuo".to_string(), skill_id: "skill_hua_tuo_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "hua_tuo".to_string(), skill_id: "skill_hua_tuo_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Tào Tháo
        CardTemplateSkillRow { card_template_id: "cao_cao".to_string(), skill_id: "skill_cao_cao_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "cao_cao".to_string(), skill_id: "skill_cao_cao_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Điển Vi
        CardTemplateSkillRow { card_template_id: "dian_wei".to_string(), skill_id: "skill_dian_wei_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "dian_wei".to_string(), skill_id: "skill_dian_wei_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Quách Gia
        CardTemplateSkillRow { card_template_id: "guo_jia".to_string(), skill_id: "skill_guo_jia_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "guo_jia".to_string(), skill_id: "skill_guo_jia_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Tôn Sách
        CardTemplateSkillRow { card_template_id: "sun_ce".to_string(), skill_id: "skill_sun_ce_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "sun_ce".to_string(), skill_id: "skill_sun_ce_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Lục Tốn
        CardTemplateSkillRow { card_template_id: "lu_xun".to_string(), skill_id: "skill_lu_xun_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "lu_xun".to_string(), skill_id: "skill_lu_xun_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Đại Kiều & Tiểu Kiều
        CardTemplateSkillRow { card_template_id: "da_qiao_xiao_qiao".to_string(), skill_id: "skill_da_qiao_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "da_qiao_xiao_qiao".to_string(), skill_id: "skill_da_qiao_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
        // Giả Hủ
        CardTemplateSkillRow { card_template_id: "jia_xu".to_string(), skill_id: "skill_jia_xu_normal".to_string(), unlock_at_star: 1, slot_type: "NORMAL".to_string() },
        CardTemplateSkillRow { card_template_id: "jia_xu".to_string(), skill_id: "skill_jia_xu_ult".to_string(), unlock_at_star: 1, slot_type: "ULTIMATE".to_string() },
    ]
}

/// Returns default formation synergies (kích duyên đội hình)
pub fn default_master_synergies() -> Vec<FormationSynergyRow> {
    vec![
        FormationSynergyRow {
            synergy_id: "syn_vanguard".to_string(),
            name: "Thiết Vệ".to_string(),
            synergy_type: "CLASS".to_string(),
            trigger_count: 2,
            icon: "🛡️".to_string(),
            description: "(2) +35 Giáp cho Tiền Tuyến, +15 Giáp cho toàn đội".to_string(),
            hero_ids: vec!["zhao_yun".to_string(), "dian_wei".to_string(), "sun_ce".to_string(), "cao_cao".to_string()],
            stat_buffs: serde_json::json!({"def": 35, "team_def": 15}),
            is_active: true,
        },
        FormationSynergyRow {
            synergy_id: "syn_sharpshooter".to_string(),
            name: "Thần Xạ".to_string(),
            synergy_type: "CLASS".to_string(),
            trigger_count: 2,
            icon: "🏹".to_string(),
            description: "(2) +25% Công, +15% Tỉ Lệ Bạo Kích cho Thần Xạ".to_string(),
            hero_ids: vec!["huang_zhong".to_string()],
            stat_buffs: serde_json::json!({"atk_pct": 0.25, "crit_rate": 0.15}),
            is_active: true,
        },
        FormationSynergyRow {
            synergy_id: "syn_arcanist".to_string(),
            name: "Kỳ Môn".to_string(),
            synergy_type: "CLASS".to_string(),
            trigger_count: 2,
            icon: "⚡".to_string(),
            description: "(2) +30% Công Phép, bắt đầu trận với 30 Nộ Khí".to_string(),
            hero_ids: vec!["zhuge_liang".to_string(), "guo_jia".to_string(), "lu_xun".to_string(), "jia_xu".to_string()],
            stat_buffs: serde_json::json!({"atk_pct": 0.30, "initial_morale": 30}),
            is_active: true,
        },
        FormationSynergyRow {
            synergy_id: "syn_shadow".to_string(),
            name: "Ám Ảnh".to_string(),
            synergy_type: "CLASS".to_string(),
            trigger_count: 2,
            icon: "🗡️".to_string(),
            description: "(2) +25% Tỉ Lệ Bạo Kích, ưu tiên áp sát hàng sau".to_string(),
            hero_ids: vec!["zhang_he_yan_liang".to_string()],
            stat_buffs: serde_json::json!({"crit_rate": 0.25}),
            is_active: true,
        },
        FormationSynergyRow {
            synergy_id: "syn_divine".to_string(),
            name: "Thần Ân".to_string(),
            synergy_type: "CLASS".to_string(),
            trigger_count: 1,
            icon: "⚕️".to_string(),
            description: "(1) Hồi 20 HP mỗi lượt cho toàn đội hình".to_string(),
            hero_ids: vec!["hua_tuo".to_string(), "da_qiao_xiao_qiao".to_string()],
            stat_buffs: serde_json::json!({"hp_regen": 20}),
            is_active: true,
        },
        FormationSynergyRow {
            synergy_id: "syn_faction_shu".to_string(),
            name: "Thục Quốc Hào Kiệt".to_string(),
            synergy_type: "FACTION".to_string(),
            trigger_count: 3,
            icon: "🐉".to_string(),
            description: "(3) Tướng Thục Quốc +20% Sát thương và hồi 15 Nộ khi ra đòn".to_string(),
            hero_ids: vec!["zhao_yun".to_string(), "huang_zhong".to_string(), "zhuge_liang".to_string()],
            stat_buffs: serde_json::json!({"dmg_pct": 0.20, "hit_rage": 15}),
            is_active: true,
        },
        FormationSynergyRow {
            synergy_id: "syn_faction_wei".to_string(),
            name: "Ngụy Quốc Hùng Binh".to_string(),
            synergy_type: "FACTION".to_string(),
            trigger_count: 3,
            icon: "👑".to_string(),
            description: "(3) Tướng Ngụy Quốc +40 Giáp và có 25% làm chậm địch".to_string(),
            hero_ids: vec!["cao_cao".to_string(), "dian_wei".to_string(), "guo_jia".to_string()],
            stat_buffs: serde_json::json!({"def": 40, "slow_chance": 0.25}),
            is_active: true,
        },
        FormationSynergyRow {
            synergy_id: "syn_faction_wu".to_string(),
            name: "Đông Ngô Liệt Hỏa".to_string(),
            synergy_type: "FACTION".to_string(),
            trigger_count: 3,
            icon: "🔥".to_string(),
            description: "(3) Tướng Đông Ngô thiêu đốt mục tiêu gây 10% sát thương mỗi hiệp".to_string(),
            hero_ids: vec!["sun_ce".to_string(), "lu_xun".to_string(), "da_qiao_xiao_qiao".to_string()],
            stat_buffs: serde_json::json!({"burn_pct": 0.10, "speed": 5}),
            is_active: true,
        },
    ]
}
