[package]
name = "game-free"
version = "0.1.0"
edition = "2024"

[dependencies]
game-core = { path = "../../crates/core" }
game-logic = { path = "../../crates/game_logic" }
game-protocol = { path = "../../crates/protocol" }
game-data-schema = { path = "../../crates/data_schema" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

bevy = { version = "0.15", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gizmos",
    "bevy_gltf",
    "bevy_mesh_picking_backend",
    "bevy_pbr",
    "bevy_picking",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_sprite_picking_backend",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_ui_picking_backend",
    "bevy_window",
    "bevy_winit",
    "custom_cursor",
    "default_font",
    "hdr",
    "multi_threaded",
    "png",
    "smaa_luts",
    "sysinfo_plugin",
    "tonemapping_luts",
] }


[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
getrandom = { version = "0.3", features = ["wasm_js"] }
bevy = { version = "0.15", default-features = false, features = ["webgl2"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { version = "0.15", default-features = false, features = ["x11"] }
